db:
  image: mysql:latest
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_DATABASE=rdoc
server:
  #Docker-sails supports several different tags:
  #0.10.32/33/34 (node 0.10.32), stable (latest node 0.10.x), latest (latest node 0.11.x)
  #0.10.32/33/34-pm2 (node 0.10.32), stable-pm2 (latest node 0.10.x), latest-pm2 (latest node 0.11.x)
  build: .
  command: node app.js --verbose
  volumes:
    - .:/server
  ports:
    - "1337:1337"
  environment:
    NODE_ENV: dev
  #For a future version
  #environment:
  #  - VIRTUAL_HOST=sails
  #  - VIRTUAL_PORT=1337
  links:
    - db
